version: '3.7'

services:
  web-cliente:
    container_name: 'emi-web-client'
    build: ./web-cliente
    restart: always
    ports:
      - "5173:80"
    networks:
      - default
    depends_on:
      - web-api

  simulador-accesso:
    container_name: 'emi-simulador-accesso'
    restart: always
    build: './simulador-acceso'
    ports:
      - "5174:80"
    networks:
      - default
    depends_on:
      - web-api

  web-api:
    container_name: 'emi-core'
    restart: always
    build: ./WebApi
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/app/assets
    networks:
      - default
    environment:
      - TZ=America/La_Paz

  servidor-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: acceso2023
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    depends_on:
      - servidor-mysql
    image: phpmyadmin:apache
    restart: always
    environment:
      PMA_HOST: servidor-mysql
      PMA_USER: root
      PMA_PASSWORD: acceso2023
    ports:
      - "5000:80"
    networks:
        - default

networks:
  default:
