const sidebarStructure = [
  {
    id: 'usuarios',
    title: 'Usuarios',
    name: 'usuarios',
    parent: true,
    icon: 'usuarios',
    link: "/usuarios",
    isAdmin: true,
    permiso: 'usuariosSistema',
  },
  {
    id: 'permisos',
    title: 'Permisos',
    name: 'permisos',
    parent: true,
    icon: 'permiso',
    link: "/permisos",
    isAdmin: true,
    permiso: 'permisos',
  },
  {
    id: "reportes",
    title: "Reportes",
    name: "dashboard",
    parent: true,
    icon: "dasbor",
    permiso: 'reportes',
    child: [
      {
        id: "dashboard",
        title: "Estadisticas",
        name: "reportes.dashboard",
        link: "/reportes-dashboard",
        icon: "chart",
        permiso: 'reportes',
      },
      {
        id: "ingresos-carrera",
        title: "Detalle por Carrera",
        name: "reportes.ingresos-carrera",
        link: "/reportes-registros-carrera",
        icon: "carrera",
        permiso: 'reportes',
      },
      {
        id: "ingresos-eventos",
        title: "Detalle por Evento",
        name: "reportes.ingresos-eventos",
        link: "/reportes-registros-evento",
        icon: "evento",
        permiso: 'reportes',
      }
    ]
  },
  {
    id: 'carreras',
    title: 'Carreras',
    name: 'carreras',
    parent: true,
    icon: 'carreras',
    link: "/carreras",
    isAdmin: true,
    permiso: 'carreras',
  },
  {
    id: 'periodo',
    title: 'Periodos Academicos',
    name: 'periodos',
    parent: true,
    icon: 'periodo',
    link: "/periodos",
    isAdmin: true,
    permiso: 'periodosAcademicos',
  },
  {
    id: 'cursos',
    title: 'Cursos',
    name: 'cursos',
    parent: true,
    icon: 'cursos',
    link: "/cursos",
    isAdmin: false,
    permiso: 'cursos',
  },
  {
    id: 'calendario',
    title: 'Calendario',
    name: 'calendario',
    parent: true,
    icon: 'calendario',
    link: "/calendario",
    permiso: 'calendario',
  },
  {
    id: 'estudiantes',
    title: 'Estudiantes',
    name: 'estudiantes',
    parent: true,
    icon: 'estudiantes',
    link: "/estudiantes",
    permiso: 'estudiantes',
  },
  {
    id: 'licencias',
    title: 'Licencias',
    name: 'licencias',
    parent: true,
    icon: 'licencias',
    link: "/licencias",
    permiso: 'licencias'
  },
  {
    id: 'control',
    title: 'Control',
    name: 'control',
    parent: true,
    icon: 'control',
    link: "/control",
    isAdmin: true,
    permiso: 'control',
  },
  {
    id: 'logout',
    title: 'Salir',
    name: 'logout',
    logout: true,
    parent: true,
    icon: 'logout',
    permiso: 'logout',
  },
]

export { sidebarStructure };
